package com.stepup.common;

/**
 * The {@code KafkaTopics} class provides constants for Kafka topic names used in the application.
 */
public class KafkaTopics {

    /**
     * This topic is used to collect and store metrics generated by different components of the application.
     */
    public static final String METRICS_TOPIC = "metrics-topic";
}
